name: Build

env:
  CARGO_INCREMENTAL: 0

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches:
      - main # ignore branches that are in the time-rs/time repo, as they're included in push
    paths-ignore:
      - "**.md"
      - LICENSE-Apache
      - LICENSE-MIT

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) || github.event_name == 'push' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: hmarr/debug-action@v2
      - run: echo "${{ github.event.pull_request.head.repo.fork }}"

